# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(791, 557)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/main_win.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_lib = QtWidgets.QLabel(self.centralwidget)
        self.lbl_lib.setGeometry(QtCore.QRect(0, 0, 601, 21))
        self.lbl_lib.setObjectName("lbl_lib")
        self.txt_lib = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_lib.setGeometry(QtCore.QRect(0, 20, 601, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_lib.setFont(font)
        self.txt_lib.setStyleSheet("color: rgb(0, 0, 127);\n"
"background-color: rgb(170, 255, 255);")
        self.txt_lib.setText("")
        self.txt_lib.setObjectName("txt_lib")
        self.tree_lib = QtWidgets.QTreeWidget(self.centralwidget)
        self.tree_lib.setGeometry(QtCore.QRect(0, 110, 401, 281))
        self.tree_lib.setObjectName("tree_lib")
        self.tree_lib.headerItem().setText(0, "1")
        self.txt_find = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_find.setGeometry(QtCore.QRect(0, 80, 181, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_find.setFont(font)
        self.txt_find.setStyleSheet("color: rgb(0, 0, 127);\n"
"background-color: rgb(170, 255, 255);")
        self.txt_find.setText("")
        self.txt_find.setObjectName("txt_find")
        self.ln_sep = QtWidgets.QFrame(self.centralwidget)
        self.ln_sep.setGeometry(QtCore.QRect(400, 110, 4, 281))
        self.ln_sep.setCursor(QtGui.QCursor(QtCore.Qt.SplitHCursor))
        self.ln_sep.setLineWidth(0)
        self.ln_sep.setMidLineWidth(0)
        self.ln_sep.setFrameShape(QtWidgets.QFrame.VLine)
        self.ln_sep.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.ln_sep.setObjectName("ln_sep")
        self.txt_info = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_info.setGeometry(QtCore.QRect(400, 110, 191, 281))
        self.txt_info.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txt_info.setToolTip("")
        self.txt_info.setStyleSheet("background-color: rgb(208, 208, 208);")
        self.txt_info.setObjectName("txt_info")
        self.btn_analyze = QtWidgets.QPushButton(self.centralwidget)
        self.btn_analyze.setGeometry(QtCore.QRect(0, 50, 151, 30))
        self.btn_analyze.setFocusPolicy(QtCore.Qt.ClickFocus)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/inspect.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_analyze.setIcon(icon1)
        self.btn_analyze.setObjectName("btn_analyze")
        self.lbl_items_analyzed = QtWidgets.QLabel(self.centralwidget)
        self.lbl_items_analyzed.setGeometry(QtCore.QRect(170, 50, 301, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lbl_items_analyzed.setPalette(palette)
        self.lbl_items_analyzed.setObjectName("lbl_items_analyzed")
        self.frm_find = QtWidgets.QFrame(self.centralwidget)
        self.frm_find.setGeometry(QtCore.QRect(230, 410, 290, 120))
        self.frm_find.setAutoFillBackground(False)
        self.frm_find.setStyleSheet("background-color: rgba(122, 255, 115, 95);")
        self.frm_find.setFrameShape(QtWidgets.QFrame.Box)
        self.frm_find.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frm_find.setObjectName("frm_find")
        self.lbl_find_caption = QtWidgets.QLabel(self.frm_find)
        self.lbl_find_caption.setGeometry(QtCore.QRect(0, 0, 290, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.lbl_find_caption.setFont(font)
        self.lbl_find_caption.setStyleSheet("color: rgb(0, 85, 0);\n"
"background-color: rgba(122, 255, 115, 95);")
        self.lbl_find_caption.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_find_caption.setObjectName("lbl_find_caption")
        self.lbl_goto_icon = QtWidgets.QLabel(self.frm_find)
        self.lbl_goto_icon.setGeometry(QtCore.QRect(239, 0, 50, 40))
        self.lbl_goto_icon.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.lbl_goto_icon.setText("")
        self.lbl_goto_icon.setPixmap(QtGui.QPixmap("img/goto.png"))
        self.lbl_goto_icon.setScaledContents(True)
        self.lbl_goto_icon.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_goto_icon.setObjectName("lbl_goto_icon")
        self.lbl_find_full_name = QtWidgets.QLabel(self.frm_find)
        self.lbl_find_full_name.setGeometry(QtCore.QRect(0, 89, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.lbl_find_full_name.setFont(font)
        self.lbl_find_full_name.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgba(122, 255, 115, 95);")
        self.lbl_find_full_name.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_find_full_name.setObjectName("lbl_find_full_name")
        self.lbl_goto_icon2 = QtWidgets.QLabel(self.frm_find)
        self.lbl_goto_icon2.setGeometry(QtCore.QRect(0, 0, 61, 60))
        self.lbl_goto_icon2.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.lbl_goto_icon2.setText("")
        self.lbl_goto_icon2.setPixmap(QtGui.QPixmap("img/search.png"))
        self.lbl_goto_icon2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_goto_icon2.setObjectName("lbl_goto_icon2")
        self.lbl_find = QtWidgets.QLabel(self.frm_find)
        self.lbl_find.setGeometry(QtCore.QRect(0, 30, 291, 61))
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.lbl_find.setFont(font)
        self.lbl_find.setStyleSheet("color: rgb(0, 0, 127);\n"
"background-color: rgba(122, 255, 115, 95);")
        self.lbl_find.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_find.setObjectName("lbl_find")
        self.lbl_lib.raise_()
        self.txt_lib.raise_()
        self.tree_lib.raise_()
        self.txt_find.raise_()
        self.txt_info.raise_()
        self.ln_sep.raise_()
        self.btn_analyze.raise_()
        self.lbl_items_analyzed.raise_()
        self.frm_find.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.txt_lib, self.txt_find)
        MainWindow.setTabOrder(self.txt_find, self.tree_lib)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Library analyzer"))
        self.lbl_lib.setText(_translate("MainWindow", "Enter any library, class, function..."))
        self.txt_lib.setToolTip(_translate("MainWindow", "Enter the name of the library you want to examine and hit Return.\n"
"Example:\n"
"    datetime\n"
"or\n"
"    sys\n"
"or\n"
"    matplotlib\n"
"You can also choose a certain part of the library.\n"
"Example:\n"
"    datetime.datetime\n"
"or\n"
"    matplotlib.pie\n"
"and you can also write:\n"
"    from datetime import datetime\n"
"or\n"
"    from PyQt5.QtCore import QThread\n"
"\n"
"Note, Use the up and down arrows to navigate through your previous entries"))
        self.txt_find.setToolTip(_translate("MainWindow", "Type expresion you want to search for in search box and hit Return.\n"
"\n"
"Note, Use the up and down arrows to navigate through your previous entries"))
        self.txt_find.setPlaceholderText(_translate("MainWindow", "Find..."))
        self.btn_analyze.setToolTip(_translate("MainWindow", "Confirm your entry by clicking the button or press return in the input field."))
        self.btn_analyze.setText(_translate("MainWindow", "Analyze library"))
        self.lbl_items_analyzed.setText(_translate("MainWindow", "0 items analyzed."))
        self.lbl_find_caption.setText(_translate("MainWindow", "Find"))
        self.lbl_find_full_name.setText(_translate("MainWindow", "PyQt5"))
        self.lbl_find.setText(_translate("MainWindow", "PyQt5"))
