from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1191, 745)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/main_win.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_lib = QtWidgets.QLabel(self.centralwidget)
        self.lbl_lib.setGeometry(QtCore.QRect(0, 0, 601, 21))
        self.lbl_lib.setObjectName("lbl_lib")
        self.txt_lib = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_lib.setGeometry(QtCore.QRect(0, 20, 601, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_lib.setFont(font)
        self.txt_lib.setStyleSheet("color: rgb(0, 0, 127);\n"
"background-color: rgb(170, 255, 255);")
        self.txt_lib.setText("")
        self.txt_lib.setObjectName("txt_lib")
        self.tree_lib = QtWidgets.QTreeWidget(self.centralwidget)
        self.tree_lib.setGeometry(QtCore.QRect(0, 110, 401, 281))
        self.tree_lib.setObjectName("tree_lib")
        self.tree_lib.headerItem().setText(0, "1")
        self.txt_find = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_find.setGeometry(QtCore.QRect(0, 80, 181, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_find.setFont(font)
        self.txt_find.setStyleSheet("color: rgb(0, 0, 127);\n"
"background-color: rgb(170, 255, 255);")
        self.txt_find.setText("")
        self.txt_find.setObjectName("txt_find")
        self.ln_sep = QtWidgets.QFrame(self.centralwidget)
        self.ln_sep.setGeometry(QtCore.QRect(400, 110, 4, 281))
        self.ln_sep.setCursor(QtGui.QCursor(QtCore.Qt.SplitHCursor))
        self.ln_sep.setLineWidth(0)
        self.ln_sep.setMidLineWidth(0)
        self.ln_sep.setFrameShape(QtWidgets.QFrame.VLine)
        self.ln_sep.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.ln_sep.setObjectName("ln_sep")
        self.txt_info = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_info.setGeometry(QtCore.QRect(400, 110, 301, 281))
        self.txt_info.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txt_info.setToolTip("")
        self.txt_info.setStyleSheet("background-color: rgb(208, 208, 208);")
        self.txt_info.setReadOnly(True)
        self.txt_info.setObjectName("txt_info")
        self.btn_analyze = QtWidgets.QPushButton(self.centralwidget)
        self.btn_analyze.setGeometry(QtCore.QRect(0, 50, 151, 30))
        self.btn_analyze.setFocusPolicy(QtCore.Qt.ClickFocus)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/inspect.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_analyze.setIcon(icon1)
        self.btn_analyze.setObjectName("btn_analyze")
        self.lbl_items_analyzed = QtWidgets.QLabel(self.centralwidget)
        self.lbl_items_analyzed.setGeometry(QtCore.QRect(170, 50, 301, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lbl_items_analyzed.setPalette(palette)
        self.lbl_items_analyzed.setObjectName("lbl_items_analyzed")
        self.frm_find = QtWidgets.QFrame(self.centralwidget)
        self.frm_find.setGeometry(QtCore.QRect(230, 430, 290, 120))
        self.frm_find.setAutoFillBackground(False)
        self.frm_find.setStyleSheet("background-color: rgba(122, 255, 115, 95);")
        self.frm_find.setFrameShape(QtWidgets.QFrame.Box)
        self.frm_find.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frm_find.setObjectName("frm_find")
        self.lbl_find_caption = QtWidgets.QLabel(self.frm_find)
        self.lbl_find_caption.setGeometry(QtCore.QRect(0, 0, 290, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.lbl_find_caption.setFont(font)
        self.lbl_find_caption.setStyleSheet("color: rgb(0, 85, 0);\n"
"background-color: rgba(122, 255, 115, 95);")
        self.lbl_find_caption.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_find_caption.setObjectName("lbl_find_caption")
        self.lbl_goto_icon = QtWidgets.QLabel(self.frm_find)
        self.lbl_goto_icon.setGeometry(QtCore.QRect(239, 0, 50, 40))
        self.lbl_goto_icon.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.lbl_goto_icon.setText("")
        self.lbl_goto_icon.setPixmap(QtGui.QPixmap("img/goto.png"))
        self.lbl_goto_icon.setScaledContents(True)
        self.lbl_goto_icon.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_goto_icon.setObjectName("lbl_goto_icon")
        self.lbl_find_full_name = QtWidgets.QLabel(self.frm_find)
        self.lbl_find_full_name.setGeometry(QtCore.QRect(0, 89, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.lbl_find_full_name.setFont(font)
        self.lbl_find_full_name.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgba(122, 255, 115, 95);")
        self.lbl_find_full_name.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_find_full_name.setObjectName("lbl_find_full_name")
        self.lbl_goto_icon2 = QtWidgets.QLabel(self.frm_find)
        self.lbl_goto_icon2.setGeometry(QtCore.QRect(0, 0, 61, 60))
        self.lbl_goto_icon2.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.lbl_goto_icon2.setText("")
        self.lbl_goto_icon2.setPixmap(QtGui.QPixmap("img/search.png"))
        self.lbl_goto_icon2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_goto_icon2.setObjectName("lbl_goto_icon2")
        self.lbl_find = QtWidgets.QLabel(self.frm_find)
        self.lbl_find.setGeometry(QtCore.QRect(0, 30, 291, 61))
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.lbl_find.setFont(font)
        self.lbl_find.setStyleSheet("color: rgb(0, 0, 127);\n"
"background-color: rgba(122, 255, 115, 95);")
        self.lbl_find.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_find.setObjectName("lbl_find")
        self.frm_net = QtWidgets.QFrame(self.centralwidget)
        self.frm_net.setGeometry(QtCore.QRect(400, 50, 491, 61))
        self.frm_net.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_net.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_net.setObjectName("frm_net")
        self.lbl_net_caption = QtWidgets.QLabel(self.frm_net)
        self.lbl_net_caption.setGeometry(QtCore.QRect(4, 0, 310, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lbl_net_caption.setPalette(palette)
        self.lbl_net_caption.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_net_caption.setObjectName("lbl_net_caption")
        self.btn_net_doc = QtWidgets.QPushButton(self.frm_net)
        self.btn_net_doc.setGeometry(QtCore.QRect(0, 27, 150, 31))
        self.btn_net_doc.setStyleSheet("color: rgb(0, 0, 127);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("img/documentation.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_net_doc.setIcon(icon2)
        self.btn_net_doc.setIconSize(QtCore.QSize(26, 26))
        self.btn_net_doc.setObjectName("btn_net_doc")
        self.btn_net_code = QtWidgets.QPushButton(self.frm_net)
        self.btn_net_code.setGeometry(QtCore.QRect(160, 27, 150, 31))
        self.btn_net_code.setStyleSheet("color: rgb(0, 0, 127);")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("img/code_example.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_net_code.setIcon(icon3)
        self.btn_net_code.setIconSize(QtCore.QSize(26, 26))
        self.btn_net_code.setObjectName("btn_net_code")
        self.lbl_f_name = QtWidgets.QLabel(self.frm_net)
        self.lbl_f_name.setGeometry(QtCore.QRect(350, 5, 131, 31))
        self.lbl_f_name.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.lbl_f_name.setObjectName("lbl_f_name")
        self.btn_setting = QtWidgets.QPushButton(self.frm_net)
        self.btn_setting.setGeometry(QtCore.QRect(315, 30, 31, 28))
        self.btn_setting.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("img/setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_setting.setIcon(icon4)
        self.btn_setting.setIconSize(QtCore.QSize(20, 20))
        self.btn_setting.setObjectName("btn_setting")
        self.lbl_f_size = QtWidgets.QLabel(self.frm_net)
        self.lbl_f_size.setGeometry(QtCore.QRect(350, 40, 81, 16))
        self.lbl_f_size.setObjectName("lbl_f_size")
        self.btn_abort = QtWidgets.QPushButton(self.frm_net)
        self.btn_abort.setGeometry(QtCore.QRect(0, 0, 481, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.btn_abort.setFont(font)
        self.btn_abort.setStyleSheet("color: rgb(255, 0, 0);")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("img/abort.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_abort.setIcon(icon5)
        self.btn_abort.setIconSize(QtCore.QSize(70, 70))
        self.btn_abort.setObjectName("btn_abort")
        self.frm_navigation = QtWidgets.QFrame(self.centralwidget)
        self.frm_navigation.setGeometry(QtCore.QRect(930, 50, 171, 61))
        self.frm_navigation.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frm_navigation.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_navigation.setObjectName("frm_navigation")
        self.btn_nav_left = QtWidgets.QPushButton(self.frm_navigation)
        self.btn_nav_left.setGeometry(QtCore.QRect(0, 10, 51, 51))
        self.btn_nav_left.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("img/nav_left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_nav_left.setIcon(icon6)
        self.btn_nav_left.setIconSize(QtCore.QSize(50, 50))
        self.btn_nav_left.setFlat(True)
        self.btn_nav_left.setObjectName("btn_nav_left")
        self.btn_nav_right = QtWidgets.QPushButton(self.frm_navigation)
        self.btn_nav_right.setGeometry(QtCore.QRect(50, 10, 51, 51))
        self.btn_nav_right.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("img/nav_right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_nav_right.setIcon(icon7)
        self.btn_nav_right.setIconSize(QtCore.QSize(50, 50))
        self.btn_nav_right.setFlat(True)
        self.btn_nav_right.setObjectName("btn_nav_right")
        self.btn_nav_end = QtWidgets.QPushButton(self.frm_navigation)
        self.btn_nav_end.setGeometry(QtCore.QRect(110, 10, 51, 51))
        self.btn_nav_end.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("img/nav_end.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_nav_end.setIcon(icon8)
        self.btn_nav_end.setIconSize(QtCore.QSize(40, 40))
        self.btn_nav_end.setFlat(True)
        self.btn_nav_end.setObjectName("btn_nav_end")
        self.frm_setting = QtWidgets.QFrame(self.centralwidget)
        self.frm_setting.setGeometry(QtCore.QRect(110, 210, 780, 430))
        self.frm_setting.setStyleSheet("background-color: rgb(155, 155, 255);")
        self.frm_setting.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_setting.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_setting.setObjectName("frm_setting")
        self.txt_setting_info = QtWidgets.QTextEdit(self.frm_setting)
        self.txt_setting_info.setGeometry(QtCore.QRect(10, 170, 761, 211))
        self.txt_setting_info.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 170, 0);")
        self.txt_setting_info.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.txt_setting_info.setObjectName("txt_setting_info")
        self.cmb_setting_font_size = QtWidgets.QComboBox(self.frm_setting)
        self.cmb_setting_font_size.setGeometry(QtCore.QRect(700, 130, 71, 31))
        self.cmb_setting_font_size.setObjectName("cmb_setting_font_size")
        self.lbl_font_name = QtWidgets.QLabel(self.frm_setting)
        self.lbl_font_name.setGeometry(QtCore.QRect(10, 106, 681, 21))
        self.lbl_font_name.setObjectName("lbl_font_name")
        self.lbl_size = QtWidgets.QLabel(self.frm_setting)
        self.lbl_size.setGeometry(QtCore.QRect(700, 106, 71, 21))
        self.lbl_size.setObjectName("lbl_size")
        self.lbl_setting_caption = QtWidgets.QLabel(self.frm_setting)
        self.lbl_setting_caption.setGeometry(QtCore.QRect(0, 0, 781, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_setting_caption.setFont(font)
        self.lbl_setting_caption.setStyleSheet("background-color: rgb(171, 171, 171);")
        self.lbl_setting_caption.setTextFormat(QtCore.Qt.AutoText)
        self.lbl_setting_caption.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_setting_caption.setObjectName("lbl_setting_caption")
        self.lbl_web_site = QtWidgets.QLabel(self.frm_setting)
        self.lbl_web_site.setGeometry(QtCore.QRect(10, 40, 541, 16))
        self.lbl_web_site.setObjectName("lbl_web_site")
        self.cmb_setting_web_site = QtWidgets.QComboBox(self.frm_setting)
        self.cmb_setting_web_site.setGeometry(QtCore.QRect(10, 60, 761, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cmb_setting_web_site.setFont(font)
        self.cmb_setting_web_site.setObjectName("cmb_setting_web_site")
        self.btn_setting_ok = QtWidgets.QPushButton(self.frm_setting)
        self.btn_setting_ok.setGeometry(QtCore.QRect(580, 390, 93, 28))
        self.btn_setting_ok.setStyleSheet("background-color: rgb(198, 198, 198);")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("img/ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_setting_ok.setIcon(icon9)
        self.btn_setting_ok.setObjectName("btn_setting_ok")
        self.btn_setting_cancel = QtWidgets.QPushButton(self.frm_setting)
        self.btn_setting_cancel.setGeometry(QtCore.QRect(680, 390, 93, 28))
        self.btn_setting_cancel.setStyleSheet("background-color: rgb(198, 198, 198);")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("img/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_setting_cancel.setIcon(icon10)
        self.btn_setting_cancel.setObjectName("btn_setting_cancel")
        self.btn_setting_close = QtWidgets.QPushButton(self.frm_setting)
        self.btn_setting_close.setGeometry(QtCore.QRect(744, 1, 34, 28))
        self.btn_setting_close.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("img/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_setting_close.setIcon(icon11)
        self.btn_setting_close.setIconSize(QtCore.QSize(30, 30))
        self.btn_setting_close.setObjectName("btn_setting_close")
        self.cmb_setting_font_name = QtWidgets.QComboBox(self.frm_setting)
        self.cmb_setting_font_name.setGeometry(QtCore.QRect(10, 130, 681, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cmb_setting_font_name.setFont(font)
        self.cmb_setting_font_name.setObjectName("cmb_setting_font_name")
        self.lbl_lib.raise_()
        self.txt_lib.raise_()
        self.tree_lib.raise_()
        self.txt_find.raise_()
        self.txt_info.raise_()
        self.ln_sep.raise_()
        self.btn_analyze.raise_()
        self.lbl_items_analyzed.raise_()
        self.frm_find.raise_()
        self.frm_net.raise_()
        self.frm_navigation.raise_()
        self.frm_setting.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.txt_lib, self.txt_find)
        MainWindow.setTabOrder(self.txt_find, self.tree_lib)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Library analyzer"))
        self.lbl_lib.setText(_translate("MainWindow", "Enter any library, class, function..."))
        self.txt_lib.setToolTip(_translate("MainWindow", "Enter the name of the library you want to examine and hit Return.\n"
"Example:\n"
"    datetime\n"
"or\n"
"    sys\n"
"or\n"
"    matplotlib\n"
"You can also choose a certain part of the library.\n"
"Example:\n"
"    datetime.datetime\n"
"or\n"
"    matplotlib.pie\n"
"and you can also write:\n"
"    from datetime import datetime\n"
"or\n"
"    from PyQt5.QtCore import QThread\n"
"\n"
"Note, Use the up and down arrows to navigate through your previous entries"))
        self.txt_find.setToolTip(_translate("MainWindow", "Type expresion you want to search for in search box and hit Return.\n"
"\n"
"Note, Use the up and down arrows to navigate through your previous entries"))
        self.txt_find.setPlaceholderText(_translate("MainWindow", "Find..."))
        self.btn_analyze.setToolTip(_translate("MainWindow", "Confirm your entry by clicking the button or press return in the input field."))
        self.btn_analyze.setText(_translate("MainWindow", "Analyze library"))
        self.lbl_items_analyzed.setText(_translate("MainWindow", "0 items analyzed."))
        self.frm_find.setToolTip(_translate("MainWindow", "Find this object in Tree View"))
        self.lbl_find_caption.setText(_translate("MainWindow", "Find"))
        self.lbl_find_full_name.setText(_translate("MainWindow", "PyQt5"))
        self.lbl_find.setText(_translate("MainWindow", "PyQt5"))
        self.lbl_net_caption.setText(_translate("MainWindow", "Online search for "))
        self.btn_net_doc.setToolTip(_translate("MainWindow", "Find online documentation for the currently selected object"))
        self.btn_net_doc.setText(_translate("MainWindow", "Documentation"))
        self.btn_net_code.setToolTip(_translate("MainWindow", "Find online code examples that use the currently selected object"))
        self.btn_net_code.setText(_translate("MainWindow", "Code Example"))
        self.lbl_f_name.setText(_translate("MainWindow", "Font name"))
        self.lbl_f_size.setText(_translate("MainWindow", "Size="))
        self.btn_abort.setToolTip(_translate("MainWindow", "Terminates the execution of an operation in progress"))
        self.btn_abort.setText(_translate("MainWindow", "Abort"))
        self.btn_nav_left.setToolTip(_translate("MainWindow", "Move one page backward"))
        self.btn_nav_right.setToolTip(_translate("MainWindow", "Move one page forward"))
        self.btn_nav_end.setToolTip(_translate("MainWindow", "Go to the last page"))
        self.txt_setting_info.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; color:#00aa00;\"># Code Example Font</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#d4d4d4;\">    </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#569cd6;\">def</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#d4d4d4;\"> </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#dcdcaa;\">set_font</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#d4d4d4;\">(</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#9cdcfe;\">family</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#d4d4d4;\">: </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#4ec9b0;\">str</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#d4d4d4;\">, </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#9cdcfe;\">size</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#d4d4d4;\">: </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#4ec9b0;\">int</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#d4d4d4;\">) -&gt; </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#4ec9b0;\">QtGui</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#d4d4d4;\">.</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#4ec9b0;\">QFont</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#d4d4d4;\">:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d4d4d4;\">        </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#9cdcfe;\">font</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d4d4d4;\">.</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#dcdcaa;\">setFamily</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d4d4d4;\">()</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d4d4d4;\">        </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#9cdcfe;\">font</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d4d4d4;\">.</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#dcdcaa;\">setPointSize</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d4d4d4;\">()</span></p></body></html>"))
        self.lbl_font_name.setText(_translate("MainWindow", "Select font:    ...    please choose a fixed-width font for better code display....like Roboto Mono or Fixed Sys"))
        self.lbl_size.setText(_translate("MainWindow", "Size:"))
        self.lbl_setting_caption.setText(_translate("MainWindow", "Code Example View - Settings"))
        self.lbl_web_site.setText(_translate("MainWindow", "Website to search:"))
        self.btn_setting_ok.setText(_translate("MainWindow", "Ok"))
        self.btn_setting_cancel.setText(_translate("MainWindow", "Cancel"))
